version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=flask
      - FLASK_ENV=development
    expose:
      - 8080
      - 9191

  lateststore:
    build: ./lateststore
    container_name: lateststore
    restart: always
    environment:
      - APP_NAME=flask
      - FLASK_ENV=development
    expose:
      - 8001

  date:
    build: ./date
    container_name: date
    restart: always
    environment:
      - APP_NAME=flask
      - FLASK_ENV=development
    expose:
      - 8002

  book:
    build: ./book
    container_name: book
    restart: always
    environment:
      - APP_NAME=flask
      - FLASK_ENV=development
    expose:
      - 8003

  updateentityauto:
    build: ./updateentityauto
    container_name: updateentityauto
    restart: always
    environment:
      - APP_NAME=flask
      - FLASK_ENV=development
    expose:
      - 8004

  nginx:
    build: ./nginx
    container_name: nginx
    # to appoint localhost to host machine
    # network_mode: host
    restart: always
    #map ports on the host machine to container itself
    #map HOST:CONTAINER
    #nginx is listening on port 80 and will proxy
    #the request to flask container @ 8080
    ports:
      ["5000:80"]